name = "LFAToolkit"
uuid = "3f92b583-c0aa-4596-8bdf-f02f6c0a52df"
authors = ["Jeremy L Thompson <thompson.jeremy.luke@gmail.com>"]
version = "0.1.0"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
