name: Julia CI

on: [push, pull_request]

jobs:
  # testing
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1', 'nightly']
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - name: Environment setup
        uses: actions/checkout@v2
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
      - name: CodeCov
        uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # style
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        uses: actions/checkout@v2
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
      - name: Check style
        run: julia .Style.jl --color=yes && git diff --exit-code src test examples docs

  # documentation
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        uses: actions/checkout@v2
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Build and deploy documentation
        uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
