name: Julia CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1', 'nightly']
        julia-arch: [x86]
        os: [ubuntu-latest]

    steps:
      - name: env setup
        uses: actions/checkout@v2
      - name: julia setup
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: build package
        uses: julia-actions/julia-buildpkg@latest
      - name: run tests
        uses: julia-actions/julia-runtest@latest
