name: Julia CI

on: [push, pull_request]

jobs:
  # testing
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1', 'nightly']
        julia-arch: [x86]
        os: [ubuntu-latest]

    steps:
      - name: Env setup
        uses: actions/checkout@v2
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia --project --color=yes -e 'using Pkg; Pkg.test("LFAToolkit"; coverage=true)'
      - name: CodeCov
        uses: codecov/codecov-action@v1

  # style
  style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x86]
        os: [ubuntu-latest]

    steps:
      - name: Env setup
        uses: actions/checkout@v2
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Check style
        run: julia .Style.jl --color=yes && git diff --exit-code src test examples docs
